### ISSUE TITLE
Office31 results

### ISSUE THREAD

**Issue by andreamaracani** [ispc-lab/BMD#2]
Good morning, I am trying to reproduce the Office31 results of the paper but I am getting lower accuracy for every domain-pair. I am using the released code and the hparams written in the paper. Do you have any suggestions on what can be the cause of this? What version of CUDA did you use?
Thank you

**Comment by andreamaracani** [comment]
In particular I report the results that I get:

| | AD | AW | DA | DW | WA | WD |AVG|
|------|------| -----|------| ------|-----| -----|-----| 
PAPER | 95.6 | 93.0 | 75.6 | 97.5 | 75.0 | 99.8 |89.4|
Repr |  91.4 | 90.7 | 73.4 | 94.2 | 70.1 |  97.6| 86.2 |
Repr* | 93.6| 91.6| 75.2| 95.0| 74.6| 99.8|88.3 |

Where Repr is my reproduction with the code as it is, while Repr* is the reproduction with the suggested loss modification (that I found in the other issue).

**Comment by sanqingqu** [comment]
Thanks for your interest in our work~~
Sorry for the late reply. We have conducted experiments on RTX-3090 with torch-1.7 and torch-1.10. 
[Here is the configuration file about our environment.](https://drive.google.com/file/d/1IwKADDxjInX-wxbgINqIWK-xEt-3Rmav/view?usp=sharing)
